
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSMULTIPEXPOENTDIVDIV EXPOENT FLOAT LPAREN MINUS MULTIP NUMBER PLUS RPARENexp : exp PLUS exp MULTIP expexp : exp PLUS exp\n                  | exp MINUS expexp : exp MULTIP exp\n              | exp DIV exp exp : LPAREN exp RPARENexp : NUMBERexp : FLOATexp : exp EXPOENT exp'
    
_lr_action_items = {'LPAREN':([0,2,5,6,7,8,9,17,],[2,2,2,2,2,2,2,2,]),'NUMBER':([0,2,5,6,7,8,9,17,],[3,3,3,3,3,3,3,3,]),'FLOAT':([0,2,5,6,7,8,9,17,],[4,4,4,4,4,4,4,4,]),'$end':([1,3,4,11,12,13,14,15,16,18,],[0,-7,-8,-2,-4,-3,-5,-9,-6,-1,]),'PLUS':([1,3,4,10,11,12,13,14,15,16,18,],[5,-7,-8,5,-2,-4,-3,-5,-9,-6,-1,]),'MINUS':([1,3,4,10,11,12,13,14,15,16,18,],[7,-7,-8,7,-2,-4,-3,-5,-9,-6,-1,]),'MULTIP':([1,3,4,10,11,12,13,14,15,16,18,],[6,-7,-8,6,-2,-4,-3,-5,-9,-6,-1,]),'DIV':([1,3,4,10,11,12,13,14,15,16,18,],[8,-7,-8,8,-2,-4,-3,-5,-9,-6,-1,]),'EXPOENT':([1,3,4,10,11,12,13,14,15,16,18,],[9,-7,-8,9,-2,-4,-3,-5,-9,-6,-1,]),'RPAREN':([3,4,10,11,12,13,14,15,16,18,],[-7,-8,16,-2,-4,-3,-5,-9,-6,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,2,5,6,7,8,9,17,],[1,10,11,12,13,14,15,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> exp PLUS exp MULTIP exp','exp',5,'p_exp_multi_plus','CACULADORA.py',53),
  ('exp -> exp PLUS exp','exp',3,'p_exp_ops','CACULADORA.py',59),
  ('exp -> exp MINUS exp','exp',3,'p_exp_ops','CACULADORA.py',60),
  ('exp -> exp MULTIP exp','exp',3,'p_exp_mult_div','CACULADORA.py',68),
  ('exp -> exp DIV exp','exp',3,'p_exp_mult_div','CACULADORA.py',69),
  ('exp -> LPAREN exp RPAREN','exp',3,'p_exp_group','CACULADORA.py',77),
  ('exp -> NUMBER','exp',1,'p_exp_number','CACULADORA.py',81),
  ('exp -> FLOAT','exp',1,'p_exp_float','CACULADORA.py',85),
  ('exp -> exp EXPOENT exp','exp',3,'p_exp_poten','CACULADORA.py',92),
]
