
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSMULTDIVPOTDIV FLOAT LPAREN MINUS MULT NUMBER PLUS POT RPARENexp : exp PLUS exp\n                  | exp MINUS exp\n                          | exp MULT exp\n                                  | exp DIV exp\n                                          | exp POT expexp : LPAREN exp RPARENexp : NUMBERexp : FLOAT'
    
_lr_action_items = {'LPAREN':([0,2,5,6,7,8,9,],[2,2,2,2,2,2,2,]),'NUMBER':([0,2,5,6,7,8,9,],[3,3,3,3,3,3,3,]),'FLOAT':([0,2,5,6,7,8,9,],[4,4,4,4,4,4,4,]),'$end':([1,3,4,11,12,13,14,15,16,],[0,-7,-8,-1,-2,-3,-4,-5,-6,]),'PLUS':([1,3,4,10,11,12,13,14,15,16,],[5,-7,-8,5,-1,-2,-3,-4,-5,-6,]),'MINUS':([1,3,4,10,11,12,13,14,15,16,],[6,-7,-8,6,-1,-2,-3,-4,-5,-6,]),'MULT':([1,3,4,10,11,12,13,14,15,16,],[7,-7,-8,7,-1,-2,-3,-4,-5,-6,]),'DIV':([1,3,4,10,11,12,13,14,15,16,],[8,-7,-8,8,-1,-2,-3,-4,-5,-6,]),'POT':([1,3,4,10,11,12,13,14,15,16,],[9,-7,-8,9,-1,-2,-3,-4,-5,-6,]),'RPAREN':([3,4,10,11,12,13,14,15,16,],[-7,-8,16,-1,-2,-3,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,2,5,6,7,8,9,],[1,10,11,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> exp PLUS exp','exp',3,'p_exp_ops','ArvoreSintatica.py',54),
  ('exp -> exp MINUS exp','exp',3,'p_exp_ops','ArvoreSintatica.py',55),
  ('exp -> exp MULT exp','exp',3,'p_exp_ops','ArvoreSintatica.py',56),
  ('exp -> exp DIV exp','exp',3,'p_exp_ops','ArvoreSintatica.py',57),
  ('exp -> exp POT exp','exp',3,'p_exp_ops','ArvoreSintatica.py',58),
  ('exp -> LPAREN exp RPAREN','exp',3,'p_exp_group','ArvoreSintatica.py',64),
  ('exp -> NUMBER','exp',1,'p_exp_number','ArvoreSintatica.py',68),
  ('exp -> FLOAT','exp',1,'p_exp_float','ArvoreSintatica.py',72),
]
